### ISSUE TITLE
Runtime exception: Unsupported SKBatteryHealth with code

### ISSUE THREAD

**Issue by waqas19921** [SensingKit/SensingKit-Android#12]
**Describe the bug**
Library is throwing runtime exception on some devices `Unsupported SKBatteryHealth with code:`

**To Reproduce**
Reproduceable on samsung phone with API level 9.0

**Expected behavior**
In case of code '9' error should not be thrown.

**Smartphone (please complete the following information):**
 - Device: [Samsung  Galaxy S8]
 - OS: Android
 - Version [9.0 (Pie)]

**Stack Trace**
```
Caused by java.lang.RuntimeException: Unsupported SKBatteryHealth with code: 9
       at org.sensingkit.sensingkitlib.data.SKBatteryStatusData$SKBatteryHealth.valueOf(SKBatteryStatusData.java:262)
       at org.sensingkit.sensingkitlib.data.SKBatteryStatusData.<init>(SKBatteryStatusData.java:314)
       at org.sensingkit.sensingkitlib.sensors.SKBatteryStatus$1.onReceive(SKBatteryStatus.java:67)
```

**Comment by waqas19921** [comment]
@minoskt Need help on this issue.

**Comment by minoskt** [comment]
Hello

You are absolutely right. I can't see what this '9' constant is in Android source code. Maybe it is a Samsung only thing.  Same case is discussed here: https://stackoverflow.com/questions/54085822/batterymanager-health-values-9.

I added a workaround for now, classifying the status as Unknown. Could you please check if it is "fixed" (i.e., does not crash any more).

Thank you
Minos

**Comment by waqas19921** [comment]
@minoskt Thanks for your help and that also fixed the crash.
